- hosts: all
  tasks:
  - name: Print creating file
    debug: msg="ansible_1.yml - Creating file in /tmp"
  - name: Creating a file with content
    copy:
      dest: "/tmp/ansible_script_file.txt"
      content: |
        = ansible_1.yml
  - name: print all env
    shell: |
      env >> /tmp/ansible_script_file.txt
      
